<a href="https://colab.research.google.com/github/lattehauma/-/blob/main/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 사전과정과 최적화

## 실수자료로의 전환(vectorization)

In [ ]:
x=[{'city':'Tokyo','temp':20.0}, {'city':'Fukuoka','temp':25.0},{'city':'Sapporo','temp':16.0}]
x
#딕셔너리 형태의 자료를 생성

[{'city': 'Tokyo', 'temp': 20.0},
 {'city': 'Fukuoka', 'temp': 25.0},
 {'city': 'Sapporo', 'temp': 16.0}]

범주형 수량화 자료로 변환
(알파벳 순서대로 변환된다)

In [ ]:
from sklearn.feature_extraction import DictVectorizer
vec=DictVectorizer(sparse=False)
#DictVectorizer이라는 클래스를 불러오는 과정
#sparse=True로 설정할 경우 데이터가 압축되어 저장됨(변환된 데이터 확인이 불가능 함)
vec.fit_transform(x)

array([[ 0.,  0.,  1., 20.],
       [ 1.,  0.,  0., 25.],
       [ 0.,  1.,  0., 16.]])

In [ ]:
vec1=DictVectorizer() #디폴트 sparse=True
x1=vec1.fit_transform(x)

sparse로 메모리공간을 줄여줄 수 있음 0이 아닌 값들의 위치를 저장함

In [ ]:
#특성변수의 이름을 확인하는 방법
x1.toarray()
vec1.get_feature_names()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['city=Fukuoka', 'city=Sapporo', 'city=Tokyo', 'temp']

텍스트 자료의 변환

In [ ]:
text=['딸기는 정말 상큼하고 맛있다',
      '바나나는 정말 달콤하고 맛있다',
      '포도는 귀엽고 맛있다',
      '딸기는 포도보다 정말 맛있다']

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vec2=CountVectorizer()
text2=vec2.fit_transform(text).toarray() #배열자료로 변경하지 않으면 위치 형태로 출력됨
import pandas as pd
text3=pd.DataFrame(text2, columns=vec2.get_feature_names())
text3

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


귀엽고  달콤하고  딸기는  맛있다  바나나는  상큼하고  정말  포도는  포도보다
0    0     0    1    1     0     1   1    0     0
1    0     1    0    1     1     0   1    0     0
2    1     0    0    1     0     0   0    1     0
3    0     0    1    1     0     0   1    0     1

특성변수의 추가

In [ ]:
import plotly.express as px
import numpy as np
x=np.array([1,2,3,4,5])
y=np.array([5,3,1,5,8])
fig=px.line(x=x,y=y)
fig.show()

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
fg=PolynomialFeatures(degree=3, include_bias=True)
#degree는 몇 차원의 추가변수를 생성할까
#include bias: y절편의 유무 
x1=fg.fit_transform(x[:,np.newaxis])
#2차원의 열 벡터로 수정하는 과정
x1

array([[  1.,   1.,   1.,   1.],
       [  1.,   2.,   4.,   8.],
       [  1.,   3.,   9.,  27.],
       [  1.,   4.,  16.,  64.],
       [  1.,   5.,  25., 125.]])

In [ ]:
from sklearn.linear_model import LinearRegression
import plotly.graph_objects as go
reg=LinearRegression()
reg.fit(x1,y)
yfit=reg.predict(x1)
fig=go.Figure()
fig.add_trace(go.Scatter(x=x,y=y, mode='lines',name='origin'))
fig.add_trace(go.Scatter(x=x,y=yfit, mode='lines+markers',name='fitted'))
fig.show()
#특성변수의 추가로 3차 그래프의 추정이 이루어짐

결측치의 처리

In [ ]:
xmiss=np.array([[None,3,5,6],[6,3,np.NaN,4],[10,32,32,25],[13,np.nan,35,23]])
xmiss

array([[None, 3, 5, 6],
       [6, 3, nan, 4],
       [10, 32, 32, 25],
       [13, nan, 35, 23]], dtype=object)

In [ ]:
from sklearn.impute import SimpleImputer
im=SimpleImputer(strategy='mean') #median, most frequent value 등 가능하다
im.fit_transform(xmiss)

array([[ 9.66666667,  3.        ,  5.        ,  6.        ],
       [ 6.        ,  3.        , 24.        ,  4.        ],
       [10.        , 32.        , 32.        , 25.        ],
       [13.        , 12.66666667, 35.        , 23.        ]])