파일 저장과 활용 방법

In [ ]:
#colab 파일 연동 방법
from google.colab import drive
drive.mount('/content/gdrive/My_Drive')

In [ ]:
######파일 생성####

##리스트 자료

In [ ]:
num=[7,2,4,7]
num.append(5) #!새로운 변수에 넣으면 리스트 성격이 사라짐
print(num)
num.sort()
num.reverse
print(num)
num.index(7) #7의 인덱스 출력
num.count(7)  #7의 빈도 출력

[7, 2, 4, 7, 5]
[2, 4, 5, 7, 7]


2

In [ ]:
num.remove(7) #첫번째 7을 삭제함
print(num)
num.pop()
print(num)
num.insert(2,9) #두번 째 자리에 삽입
print(num)
print(num*5)

In [ ]:
num2=[1,5,4,8]
num2_1=[1,5,4,8]
num3=[5,7]
num2.append(num3)
print(num2)
num2_1.extend(num3)
print(num2_1)

[1, 5, 4, 8, [5, 7]]
[1, 5, 4, 8, 5, 7]


##튜플 자료
값 변경이 불가능함
묶음기호는 ()

In [ ]:
sen='a','b','c'
k1,k2,k3=sen
print(k1)

a


##딕셔너리

key 와 value로 구성됨

In [ ]:
dict1={}
dict1['name']='sena'
dict1[11]='location'
print(dict1)
print(dict1.keys())  #values, items
del(dict1[11])
print(dict1)
print('name' in dict1)
print('sena' in dict1) #value존재 여부는 확인이 안됨

{'name': 'sena', 11: 'location'}
dict_keys(['name', 11])
{'name': 'sena'}
True
False


In [ ]:
dict2={'name':'izu'}
x=dict2.get('name')
print(x)

izu


In [ ]:
cars =[1.097,2.2634,3.235]
nations = ['Korea', 'Japan', 'America']
#zip:자료값을 이어주는 함수
for c, n in zip(cars, nations):
	print('%.2f is made in %s' %(c,n))
 #정수형일 때는 %d, 실수 일 때는 %.2f, 문자일 때는 %s

1.10 is made in Korea
2.26 is made in Japan
3.23 is made in America


##집합

In [ ]:
a={1,2,3}; b={2,3,4}
print(a|b) 
print(a&b) 
print(a-b)
a.add(4)
print(a)
a.update([5,6])
print(a)
a.remove(2)
print(a)

{1, 2, 3, 4}
{2, 3}
{1}
{1, 2, 3, 4}
{1, 2, 3, 4, 5, 6}
{1, 3, 4, 5, 6}


##문자 데이터

In [ ]:
letter="에그타르트 먹고 싶다."
print(letter[3])
print(letter[4:7])
print(letter[9:-1])
print(letter[::2])
print(letter.count(""))

르
트 먹
싶다
에타트먹 다
13


In [ ]:
print('라라랄\'')

라라랄'


In [ ]:
word="  hungr y "
print(word)
print(word.strip()) #공백제거
word2=word.replace("h","o") #문자 바꾸기
print(word2)
print(word.split("g")) #문자 나누기

  hungr y 
hungr y
  oungr y 
['  hun', 'r y ']


format 함수

In [ ]:
sen="오늘의 주가는 {lat}원이다."
sen.format(lat=2600)

'오늘의 주가는 2600원이다.'

##연산자

In [ ]:
print(1e7)
print(0.3+0.6==0.9)
#실수 계산에서 오차 발생

10000000.0
False


조건문 연산자

In [ ]:
a='b'
b='c'
c='b'
print(a is b)
print(a is c)
print(a is not b)
print('b' in a)

False
True
True
True


In [ ]:
if a == 'b':
  print("a is equal to {}".format(a))

a is equal to b


반복문

In [ ]:
for num in range(0,5):
  print(num)
a=[1,2,4,5]
print('___')
##
for i in a:
  print(i)

print('___')
##
num=0
numa=[]
while(num<5):
  numa.append(num)
  num+=1

print(numa)

##
for i in 'iloveyou':
  print(str(i))

0
1
2
3
4
___
1
2
4
5
___
[0, 1, 2, 3, 4]
i
l
o
v
e
y
o
u


In [ ]:
con=0
while(con<=10):
  if(con>3):
    break
  else:
    print(con)
  con+=1

0
1
2
3


In [ ]:
con=0
while(con<=10):
  con+=1
  if(con<5):
    continue
  else:
    print(con)

5
6
7
8
9
10
11


In [ ]:
##혜린선생님의 가르침
print([i+2 for i in range(10) if i%2])
m,n=2,3
ar1=[[1,2]*m for _ in range(n) ]
print(ar1)
ar2=[[1,2]*2]*3
print(ar2)
ar1[0][0]=5
ar2[0][0]=5
print(ar1)
print(ar2)

[3, 5, 7, 9, 11]
[[1, 2, 1, 2], [1, 2, 1, 2], [1, 2, 1, 2]]
[[1, 2, 1, 2], [1, 2, 1, 2], [1, 2, 1, 2]]
[[5, 2, 1, 2], [1, 2, 1, 2], [1, 2, 1, 2]]
[[5, 2, 1, 2], [5, 2, 1, 2], [5, 2, 1, 2]]


##함수

In [ ]:
def add(a,b):
  result=a+b
  return result

In [ ]:
#매개변수
x= lambda a:a*3
x(5)
#내부 람다 함수
def fun(n):
  return lambda a: (a*n)+n
double=fun(2)
print(double(6))


14


In [ ]:
#전역변수
a=0
def plus():
  global a
  a+=1
plus()
plus()
print(a)

2


In [ ]:
sam=['진짜 배가 고프다', '이제는 저녁을 먹어야 할 것 같다']
token={}
for s in sam:
  print(s)
  for word in s.split():
    if word not in token:
      token[word]=len(token)+1
print(token)

진짜 배가 고프다
이제는 저녁을 먹어야 할 것 같다
{'진짜': 1, '배가': 2, '고프다': 3, '이제는': 4, '저녁을': 5, '먹어야': 6, '할': 7, '것': 8, '같다': 9}


##입출력

In [ ]:
data=list(map(int, input().split('-')))
print(data)

12-53-13
[12, 53, 13]


In [ ]:
a,b,c=map(int,input().split())
print(a-b+c)

3 2 6
7


##클래스

In [ ]:
class Member:
  personal_count=0  #클래스속성
  def __init__(self, name, month):  #자동으로 실행되는 기본 함수
    self.name = name  #사례속성(변화하는 속성)
    self.month = month
    Member.personal_count += 1
m1=Member("세",12)
print(m1.name)

세


In [ ]:
class Food:
  def __init__(self, name, year, month):
    self.name=name
    self.month=month
    self.year=year

  @property
  def month(self):
    return self.__month
  
  @month.setter
  def month(self, month):
    if month<1:
      self.__month =1
    elif month>12:
      self.__month = 12
    else:
      self.__month=month
  
  def exp_date(self):
    print('exp date is ' + str(self.month))
 
food1=Food('pizza',20,12)
food1.exp_date()

exp date is 12


exp date is 12


##모듈

numpy

In [ ]:
import numpy as np
x=np.array([1,2,3])
y=np.array([6,3,7])
print(x+y)
print(type(x))
print(x.shape)

[ 7  5 10]
<class 'numpy.ndarray'>
(3,)


In [ ]:
#차원변경
ar=np.array([1,2,3,4,5,6,7,8])
ar1=ar.reshape(2,4)
print(ar1)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(np.linspace(0,1,5))
print(np.arange(0,10,2))
#특정분포를 따르는 확률변수 값 생성
print(np.random.normal(0,1,(3,3)))
print(np.random.uniform(0,10,3))
print(np.random.randint(0,10,3))

[0.   0.25 0.5  0.75 1.  ]
[0 2 4 6 8]
[[-0.15731143  0.59620204  0.61137656]
 [ 1.78757231 -1.17970809 -0.79377562]
 [-0.9711406  -0.10161405 -0.69749935]]
[5.78090398 5.89559066 5.91702185]
[0 9 0]


In [ ]:
x=np.array([[2,3],[4,0],[4,8]])
print(x[0])
print(x[0][1])

#위치검색
print(np.where(x==0))
print(np.where(x%2==1))
x.flatten

[2 3]
3
(array([1]), array([1]))
(array([0]), array([1]))


array([2, 3, 4, 0, 4, 8])

In [ ]:
for x in np.nditer(ar[:,::2]):
  print(x[x>15])?

IndexError: ignored

In [ ]:
ar=np.array([1,2,3,4,5,6,7])
print(ar[0:3])
print(ar[0:7:2])

[1 2 3]
[1 3 5 7]


데이터 타입
____
i 정수 / b 불린(false, true 형태로 출력) / u 양의 정수 / f 실수 / c 복소수 / m 시간 간격 / M 시간 간격 / O 객체 / S 문자열 / U 유니코드 문자열 / V 미지정

In [ ]:
ar1=np.array([1.1,2.31,4.123])
dr=ar1.astype("i")
print(dr)

[1 2 4]


배열

In [ ]:
ar=np.array([1,4,6,2])
ac=ar.copy()
av=ar.view()
print(ac)
print(av)

[1 4 6 2]
[1 4 6 2]


병합

In [ ]:
ar1=np.array([1,4,7])
ar2=np.array([3,2,9])
ar=np.concatenate((ar1,ar2))
print(ar)
ar3=np.stack((ar1,ar2),axis=1)
ar4=np.stack((ar1,ar2),axis=0)
print(ar3)
print(ar4)
ar5=np.hstack((ar1,ar2))
ar6=np.vstack((ar1,ar2))
print(ar5)
print(ar6)
ar6=np.dstack((ar1,ar2))
print(ar6)

[1 4 7 3 2 9]
[[1 3]
 [4 2]
 [7 9]]
[[1 4 7]
 [3 2 9]]
[1 4 7 3 2 9]
[[1 4 7]
 [3 2 9]]
[[[1 3]
  [4 2]
  [7 9]]]


분할

In [ ]:
ar=np.array([1,2,3,4,6,5])
ar1=np.array_split(ar,3)
ar2=np.split(ar,[1,5])
print(ar1)
print(ar2)


[array([1, 2]), array([3, 4]), array([6, 5])]
[array([1]), array([2, 3, 4, 6]), array([5])]


정렬

In [ ]:
ar=np.array([1,8,3,6,5,3])
print(np.sort(ar)) #원배열은 그대로 남아있음
print(np.argsort(ar)) #위치를 출력함

[1 3 3 5 6 8]
[0 2 5 4 3 1]


기초통계

In [ ]:
x=([15,35,72,43,16,42])
print(np.mean(x))
print(np.sum(x))
print(np.std(x))
print(np.var(x))
print(np.min(x))
print(np.argmin(x))  #최소값을 만들어주는 x값
print(np.median(x))

37.166666666666664
223
19.212987505562193
369.1388888888889
15
0
38.5


필터

In [ ]:
ar=np.array([67,2,34,5,35])
filter=[True,False,True,False,True]
ar1=ar[filter]
print(ar1)

[67 34 35]


In [ ]:
ar=np.array([67,2,34,5,35])
filter=[]
for x in ar:
  if x>30:
    filter.append(True)
  else:
    filter.append(False)

print(ar[filter])

[67 34 35]


In [ ]:
x=np.array([[1,2],[3,4],[5,6],[7,8]])
y=np.array([1,0,1,0])
print(x[y==1,:])

[[1 2]
 [5 6]]


In [ ]:
x=np.arange(12).reshape((3,4))
ind=np.array([1,3])
print(x)
print(x[:,~ind])  #~거꾸로

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 2  0]
 [ 6  4]
 [10  8]]


랜덤

In [ ]:
from numpy import *
r=random.randint(100,size=7)
print(r)
r_1=random.randint(100,size=(3,7))
print(r_1)

r_2=random.rand(3)
print(r_2) ##9자리 실수

r_3=random.choice([1,2,3,4,5,6,7],size=(2,5))
print(r_3)

[88  9 27 44 74 67 80]
[[76 83 26 72 31 90 57]
 [63 18 47 64 29 69 18]
 [75 56 20  2 63 40  3]]
[0.85776398 0.3610337  0.86007653]
[[3 3 7 1 1]
 [4 7 2 3 4]]


In [ ]:
from numpy import *
from pandas import *



##파일 업로드
from google.colab import files
uploaded = files.upload()

#df=pd.read_csv(‘data.csv’)

In [ ]:
import seaborn as sns

In [ ]:
df=sns.load_dataset('titanic')


## 꿔바로우씨의 라이브러리 참고하기

In [ ]:
eval("9/3**2")

1.0

In [6]:
a=[('A',7,6),('B',5,2),('C',3,4)]
sorted(a, key=lambda a: a[2])  #키 설정

[('B', 5, 2), ('C', 3, 4), ('A', 7, 6)]

순열, 조합

In [17]:
from itertools import permutations as pm #순열
from itertools import combinations as cm #조합
from itertools import product #중복순열
from itertools import combinations_with_replacement as cmr #중복조합

In [20]:
x=[1,2,3,4]
print(list(pm(x,2)))
print(list(cm(x,2)))
print(list(product(x,repeat=2)))
print(list(cmr(x,2)))


[(1, 2), (1, 3), (1, 4), (2, 1), (2, 3), (2, 4), (3, 1), (3, 2), (3, 4), (4, 1), (4, 2), (4, 3)]
[(1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4)]
[(1, 1), (1, 2), (1, 3), (1, 4), (2, 1), (2, 2), (2, 3), (2, 4), (3, 1), (3, 2), (3, 3), (3, 4), (4, 1), (4, 2), (4, 3), (4, 4)]
[(1, 1), (1, 2), (1, 3), (1, 4), (2, 2), (2, 3), (2, 4), (3, 3), (3, 4), (4, 4)]


heapq

In [28]:
import heapq


nums = [4, 1, 7, 3, 8, 5]

heap1=[]
heap2=[]
heapr=[]

for num in nums:
  heapq.heappush(heap1, num)

while heap1:
  heapq.heappop(heap1)
  print(heap1)


for num in nums:
  heapq.heappush(heap2, (-num, num))  # (우선 순위, 값)

while heap2:
  heapr.append(heapq.heappop(heap2)[1])  # index 1

print(heapr)



[3, 4, 5, 7, 8]
[4, 7, 5, 8]
[5, 7, 8]
[7, 8]
[8]
[]
[8, 7, 5, 4, 3, 1]


bisect

In [40]:
from bisect import bisect_left, bisect_right

nums = [0,0,3,5,5,5,7,8]
print(bisect_left(nums,5))
print(bisect_right(nums,5))

3
6


collections

In [44]:
from collections import deque
x=deque([1,5,7,8,33])

x.appendleft('dk')
x.append(9)

print(x)

x.popleft()
x.pop()
print(x)

deque(['dk', 1, 5, 7, 8, 33, 9])
deque([1, 5, 7, 8, 33])


In [45]:
#빈도 계산
from collections import Counter
c=Counter([1,1,1,1,1,3,3,2,5,7,7,7])
c

Counter({1: 5, 2: 1, 3: 2, 5: 1, 7: 3})

In [49]:
import math
print(math.factorial(5))
print(math.sqrt(25))
math.gcd(5,15) #최대공약수
print(math.pi)
print(math.e)


120
5.0
3.141592653589793
2.718281828459045
